name: Delivery
on: workflow_dispatch: {}
  # workflow_run:
  #   workflows: ["Build"]
  #   types:
  #     - completed
  # branches:
  #   - master
  # tags:
  #   - '*'

jobs:
  deliver:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    